# Generated by Django 4.2.16 on 2024-09-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
