# Generated by Django 4.2.16 on 2024-09-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0004_alter_movie_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="platform",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform",
                to="movies_app.platform",
            ),
            preserve_default=False,
        ),
    ]
