# Generated by Django 4.2.16 on 2024-09-30 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0005_movie_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_set",
                to="movies_app.platform",
            ),
        ),
    ]
