# Generated by Django 4.2.16 on 2024-10-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0006_alter_movie_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Bad"),
                            (2, "Average"),
                            (3, "Good"),
                            (4, "V Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
