# Generated by Django 4.2.16 on 2024-10-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0007_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="movies_app.movie",
            ),
            preserve_default=False,
        ),
    ]
