# Generated by Django 4.2.16 on 2024-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_app", "0008_review_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="total_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 - Bad"),
                    (2, "2 - Average"),
                    (3, "3 - Good"),
                    (4, "4 - V Good"),
                    (5, "5 - Excellent"),
                ]
            ),
        ),
    ]
